import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import openapiTS, { astToString } from "openapi-typescript";
import ts from "typescript";

const backendBaseUrl =
  process.env.BACKEND_API_URL ??
  process.env.NEXT_PUBLIC_API_BASE_URL ??
  "http://localhost:8000";
const openApiUrl =
  process.env.BACKEND_OPENAPI_URL ??
  new URL("/openapi.json", backendBaseUrl).toString();

const schemaOutput = resolve("types/openapi.schema.json");
const typesOutput = resolve("types/api.generated.ts");

async function ensureDir(filePath) {
  await mkdir(dirname(filePath), { recursive: true });
}

async function loadSchema() {
  const response = await fetch(openApiUrl);

  if (!response.ok) {
    throw new Error(`OpenAPI fetch failed with status ${response.status}`);
  }

  return response.json();
}

async function main() {
  try {
    const schema = await loadSchema();
    const ast = await openapiTS(schema, {
      alphabetize: true,
      transform(schemaObject) {
        const contentMediaType =
          typeof schemaObject === "object" && schemaObject
            ? "contentMediaType" in schemaObject
              ? schemaObject.contentMediaType
              : undefined
            : undefined;

        if (
          schemaObject.type === "string" &&
          (schemaObject.format === "binary" ||
            contentMediaType === "application/octet-stream")
        ) {
          return ts.factory.createTypeReferenceNode("File");
        }

        return undefined;
      },
    });
    const output = `// Generated by scripts/sync-openapi.mjs\n${astToString(ast)}`;

    await ensureDir(schemaOutput);
    await ensureDir(typesOutput);
    await writeFile(schemaOutput, `${JSON.stringify(schema, null, 2)}\n`, "utf8");
    await writeFile(typesOutput, output, "utf8");

    console.log(`OpenAPI schema synced from ${openApiUrl}`);
  } catch (error) {
    try {
      await readFile(typesOutput, "utf8");
      console.warn(
        `OpenAPI sync skipped: ${error instanceof Error ? error.message : String(error)}`,
      );
      console.warn(`Using existing generated types at ${typesOutput}`);
    } catch {
      throw error;
    }
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
